version: '3'
services:
    admindb:
        container_name: admindb
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=example
            - MYSQL_DATABASE=admin
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - TZ=Asia/Taipei
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
    web:
        depends_on:
            - admindb
            - redis
        container_name: web
        image: nginx-php7-example
        volumes:
            - "$(pwd):/var/www/app"
        ports:
            - "8000:80"
        restart: always
        environment:
            - MYSQL_HOST=admindb:3306
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
